# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :run_unit_tests do
    run_tests(
      scheme: "Movie",
      device: "iPhone 16 (18.5)",
      number_of_retries: 1,
      clean: true,
      xcodebuild_formatter: "xcpretty"
    )
  end
end